export {default as NavBar} from './NavBar/NavBar'
export {default as Hero} from './Hero/Hero'
export {default as Services} from './Services/Services'
export {default as About} from './About/About'
export {default as Pricing} from './Pricing/Pricing'
export {default as Reviews} from './Reviews/Reviews'